version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=fbd
      - MYSQL_ROOT_PASSWORD=fbd
    ports:
      - '3306:3306'
    volumes:
      - /home/djube/ppca-fbd/data:/var/lib/mysql
volumes:
  db:
    driver: local