CREATE TABLE fbd.CARGA_SENADOR (
	NOME varchar(255) NULL,
	PARTIDO varchar(100) NULL,
	UF varchar(2) NULL,
	PERIODO varchar(100) NULL,
	SEXO varchar(1) NULL,
	LEGISLATURA TINYINT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
