CREATE TABLE fbd.DESPESA (
	ID_DESPESA BIGINT auto_increment NOT NULL,
	ANO SMALLINT NOT NULL,
	MES TINYINT NOT NULL,
	ID_SENADOR BIGINT NOT NULL,
	ID_FORNECEDOR BIGINT NULL,
	ID_TIPO_DESPESA BIGINT NOT NULL,
	DATA_REEMBOLSO DATE NOT NULL,
	DOCUMENTO varchar(100) NULL,
	COD_DOCUMENTO varchar(100) NULL,
	CONSTRAINT DESPESA_PK PRIMARY KEY (ID_DESPESA),
	CONSTRAINT DESPESA_SENADOR_FK FOREIGN KEY (ID_SENADOR) REFERENCES fbd.SENADOR(ID_SENADOR),
	CONSTRAINT DESPESA_FORNECEDOR_FK FOREIGN KEY (ID_FORNECEDOR) REFERENCES fbd.FORNECEDOR(ID_FORNECEDOR),
	CONSTRAINT DESPESA_TIPO_DESPESA_FK FOREIGN KEY (ID_TIPO_DESPESA) REFERENCES fbd.TIPO_DESPESA(ID_TIPO_DESPESA)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;
