CREATE TABLE fbd.FORNECEDOR (
	ID_FORNECEDOR BIGINT auto_increment NOT NULL,
	NOME varchar(255) NOT NULL,
	CPF_CNPJ varchar(20) NULL,
	CONSTRAINT FORNECEDOR_PK PRIMARY KEY (ID_FORNECEDOR),
	CONSTRAINT FORNECEDOR_UN UNIQUE KEY (CPF_CNPJ)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;