CREATE TABLE fbd.SENADOR (
  ID_SENADOR bigint NOT NULL AUTO_INCREMENT,
  NOME varchar(255) NOT NULL,
  SEXO varchar(1) DEFAULT NULL,
  CONSTRAINT SENADOR_PK PRIMARY KEY (ID_SENADOR),
) 
ENGINE=InnoDB 
DEFAULT CHARSET=utf8mb4 
COLLATE=utf8mb4_0900_ai_ci 
AUTO_INCREMENT=1;
