CREATE TABLE fbd.TIPO_DESPESA (
	ID_TIPO_DESPESA BIGINT auto_increment NOT NULL,
	DESCRICAO varchar(255) NOT NULL,
	CONSTRAINT TIPO_DESPESA_PK PRIMARY KEY (ID_TIPO_DESPESA),
	CONSTRAINT TIPO_DESPESA_UN UNIQUE KEY (DESCRICAO)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;