DELIMITER $$

CREATE OR REPLACE VIEW fbd.VW_DESPESA_POR_LEGISLATURA AS
SELECT TP.DESCRICAO AS DESCRICAO_DESPESA, SUM(D.VALOR_REEMBOLSADO) AS VALOR_TOTAL, CONCAT(L.ANO_INICIO, " - ", L.ANO_FIM) AS LEGISLATURA  
FROM fbd.TIPO_DESPESA TP, fbd.DESPESA D, fbd.SENADOR S, 
     fbd.FORNECEDOR F, fbd.MANDATO M, fbd.LEGISLATURA L, 
     fbd.MANDATO_LEGISLATURA ML  
WHERE TP.ID_TIPO_DESPESA = D.ID_TIPO_DESPESA AND 
      D.ID_SENADOR = S.ID_SENADOR AND 
      D.ID_FORNECEDOR = F.ID_FORNECEDOR AND 
      S.ID_SENADOR = M.ID_SENADOR AND 
      M.ID_MANDATO = ML.ID_MANDATO AND 
      M.LEGISLATURA = ML.NR_LEGISLATURA AND 
      ML.NR_LEGISLATURA = L.NR_LEGISLATURA AND 
      (D.ANO BETWEEN L.ANO_INICIO AND L.ANO_FIM)
GROUP BY TP.ID_TIPO_DESPESA, L.NR_LEGISLATURA 
ORDER BY m.PERIODO DESC, VALOR_TOTAL DESC;

$$

DELIMITER ;
